apiVersion: apps/v1
kind: Deployment
metadata:
  name: ic-webapp-deploy
  labels:
    app: ic-webapp
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ic-webapp
  template:
    metadata:
      labels:
        app: ic-webapp
    spec:
      # Secret pour tirer l'image privée
      imagePullSecrets:
        - name: github-regcred
      containers:
        - name: ic-webapp
          image: eyaalimi/ic-webapp:1.0
          env:
            - name: ODOO_URL
              valueFrom:
                configMapKeyRef:
                  name: ic-webapp-cm
                  key: ODOO_URL
            - name: PGADMIN_URL
              valueFrom:
                configMapKeyRef:
                  name: ic-webapp-cm
                  key: PGADMIN_URL
          resources:
            requests:
              cpu:    "200m"    # Réduit la demande CPU pour faciliter le scheduling
              memory: "128Mi"
            limits:
              cpu:    "500m"
              memory: "256Mi"
          ports:
            - containerPort: 8080
           



