apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-cm 
  namespace: icgroup 
  labels: 
    env: prod 
    app: pgadmin 
data:
  email: odoo@eya.fr 
  servers.json: 
    {
    "Servers": {
      "1": {
        "Name": "devops projet", 
        "Group": "database group",
        "Host": "postgres-svc", 
        "Port": 5432 ,
        "MaintenanceDB": "postgres", 
        "Username": "odoo",
        "SSLMode": "prefer",
        "PASSWORD" : "odoo_password"
           }
               }
    }

