apiVersion: v1
kind: Service
metadata:
  name: pgadmin-svc 
  namespace: icgroup 
  labels: 
    env: prod 
    app: pgadmin 
spec:
  selector:
    app: pgadmin
  ports:
  - port: 80
    targetPort: 80 
    NodePort: 30011 
  type: NodePort 
