apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-cm
  labels:
    env: prod
    app: postgres
data:
  user: odoo
  password: 77u/bXlvZG9vDQo=   # Ajoute un mot de passe pour l'utilisateur 'odoo'
  databases: |
    - name: postgres
      owner: odoo
      encoding: UTF8
      locale: en_US.UTF-8
