services:
  web:
    image: odoo:17.0
    command: odoo --addons-path=/mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
    networks:
      - ic_network
    container_name: odoo_web
    depends_on:
      - mydb
    ports:
      - '8069:8069'
    environment:
      - USER=odoo
      - PASSWORD=odoo_password
      - HOST=mydb
    volumes:
      - /data_docker/config:/etc/odoo
      - c:/data_docker/addons:/mnt/extra-addons
      - odoo-web-data:/var/lib/odoo
    
  mydb:
    container_name: odoo_database
    image: postgres:15
    networks:
      - ic_network
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo_password
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    

volumes:
  odoo-web-data:
  odoo-db-data:

networks:
  ic_network:
    driver: bridge