version: '3.3'
services:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    networks:
      - ic_network
    environment:
      - PGADMIN_DEFAULT_EMAIL=odoo@eya.fr
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
    ports:
      - "80:80"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
      - pgadmin_data:/var/lib/pgadmin

networks:
  ic_network:
    driver: bridge

volumes:
  pgadmin_data:


