---
- name: docker_deploy
  hosts: docker
  become: true
  vars:
    network: webapp-network
  tasks:
    - name: Include docker variables
      include_vars:
        file: "host_vars/docker.yaml"

  roles:
    - docker
    - icwebapp
    - odoo
    - pgdamin
