version: '3.8'

services:
  jenkins:
    container_name: jenkins_ds
    image: jenkins/jenkins:2.454-jdk17
    user: root
    privileged: true  # Required for DinD in some setups
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Docker access
      - /usr/bin/docker:/usr/bin/docker            # Docker CLI (if you prefer to mount it)
    restart: always

volumes:
  jenkins_home:
