apiVersion: v1
kind: PersistentVolume
metadata:
  name: odoo-pv
  labels: 
    env: prod 
    app: odoo 
    type: local
spec:
  capacity:
    storage: 5G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: mmanual
  hostPath:
    path: /data-odoo
    
