---
all:
  children:
    prod:
      hosts:
        k3s-node:
          ansible_host: <YOUR_IP_HERE>
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ../terraform/keypair/kubernetes.pem
